GraduationProjectSkafferiet/Controllers/SkafferietController.cs
using GraduationProjectSkafferiet.Models;
using GraduationProjectSkafferiet.Views.Skafferiet;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace GraduationProjectSkafferiet.Controllers
{
    public class SkafferietController : Controller
    {
        DataService dataService;
        AccountService accountService;
        UserManager<ApplicationUser> userManager;
        public SkafferietController(DataService dataService, AccountService accountService, UserManager<ApplicationUser> userManager)
        {
            this.dataService = dataService;
            this.accountService = accountService;
            this.userManager = userManager;
        }

        [HttpGet("")]
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction(nameof(Home));
            return View();
        }
        [HttpPost("")]
        public async Task<IActionResult> IndexAsync(IndexVM viewModel)
        {
            if (!ModelState.IsValid)
                return View();

            // Try to register user
            var errorMessage = await accountService.TryRegisterAsync(viewModel);
            if (errorMessage != null)
            {
                // Show error
                ModelState.AddModelError(string.Empty, errorMessage);
                return View();
            }
            // Redirect user
            return RedirectToAction(nameof(Home));
        }
        [HttpGet("/Login")]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction(nameof(Home));
            return View();
        }
        [HttpPost("/Login")]
        public async Task<IActionResult> LoginAsync(LoginVM viewModel)
        {
            if (!ModelState.IsValid)
                return View();

            // Check if credentials is valid (and set auth cookie)
            var errorMessage = await accountService.TryLoginAsync(viewModel);
            if (errorMessage != null)
            {
                // Show error
                ModelState.AddModelError(string.Empty, errorMessage);
                return View();
            }
            // Redirect user
            return RedirectToAction(nameof(Home));
        }

        [HttpGet("Logout")]
        public IActionResult Logout()
        {
            accountService.SignOut();
            return RedirectToAction(nameof(Login));
        }

        [Authorize]
        [HttpGet("Home")]
        public async Task<IActionResult> Home()
        {
            var model = await dataService.GetIngredientsAndInventoryAsync();
            model.IsIngredientChosen = model.Inventory.Length == 0 ? false : true;
            var userId = userManager.GetUserId(HttpContext.User);
            ApplicationUser user = userManager.FindByIdAsync(userId).Result;
            model.Name = user.FirstName;
            return View(model);
        }

        [HttpPost("/Home")]
        public async Task<IActionResult> CreateAsync(HomeVM model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await dataService.AddAsync(model);
            return RedirectToAction(nameof(Index));
        }
        //[HttpGet("/ChangeCheckedTrue")]
        //public IActionResult ChangeCheckedTrue()
        //{
        //    return RedirectToAction(nameof(Home), );
        //}
        //[HttpGet("/ChangeCheckedFalse")]
        //public IActionResult ChangeCheckedFalse()
        //{
        //    return RedirectToAction(nameof(Home), model);
        //}


        [Authorize]
        [HttpGet("/Recipes")]
        public IActionResult Recipes(RecipesVM[] model)
        {
            return View(model);
        }

        [Authorize]
        [HttpPost("/Recipes")]
		public async Task<IActionResult> Recipes(HomeVM model)
		{
            var recipeModel = await dataService.GetRecipes(model.SelectedIngredients);
            return View(recipeModel);
            //return RedirectToAction(nameof(Recipes), recipeModel);
		}

        [Authorize]
        [HttpGet("/recipe")]
        public async Task<IActionResult> RecipeInfo(int id)
        {
            RecipeInfoVM vm = await dataService.GetRecipeByIdAsync(id);
            return View(vm);
        }

        [HttpGet("Delete")]
        public async Task<IActionResult> Delete(string ingredientName)
        {
            await dataService.DeleteIngredientAsync(ingredientName);
            return RedirectToAction(nameof(Index));
        }

    }
}

GraduationProjectSkafferiet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/stylesheet.css" rel="stylesheet" />
    <link href="~/css/index.css" rel="stylesheet" />
    <link href="~/css/login.css" rel="stylesheet" />
    <link href="~/css/home.css" rel="stylesheet" />
    <link href="~/css/recipes.css" rel="stylesheet" />
    <link href="~/css/recipeinfo.css" rel="stylesheet" />
    <link href="~/blobz/blobz.min.css" rel="stylesheet" />
</head>
<body class="min-vh-100">

    @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
    <div class="container-fluid">
    <div>
    <a class="navbar-brand" asp-area="" asp-controller="Skafferiet" asp-action="Index">Skafferiet🥗</a>
    @if (User.Identity.IsAuthenticated)
    {
    RenderSection("breadcrumb", false);
    }
    </div>
    <div>
    @if (User.Identity.IsAuthenticated)
    {
    <a class="btn btn-outline-primary" asp-controller="Skafferiet" asp-action="Logout">Log out</a>
    }
    @RenderSection("navbutton", false)
    </div>
    </div>
    </nav>*@

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Skafferiet" asp-action="Index">Skafferiet🥗</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <form>
                            @if (User.Identity.IsAuthenticated)
                            {
                                RenderSection("breadcrumb", false);
                            }
                        </form>
                    </li>
                </ul>
                <form>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-outline-primary" asp-controller="Skafferiet" asp-action="Logout">Log out</a>
                    }
                    @RenderSection("navbutton", false)
                </form>
            </div>
        </div>
    </nav>

    <div class="fill-view">
        @RenderBody()
    </div>


    <footer class="d-flex justify-content-between mx-2">
        <div class="col text-end align-self-center" style="text-align: right;">&copy; Skafferiet Inc. 2023. We love food!</div>
    </footer>

    @RenderSection("scripts", false)
</body>
</html>